export const countryListPt = [
    {"name": "Afeganistão", "value": "Afghanistan"},
    {"name": "África do Sul", "value": "South Africa"},
    {"name": "Albânia", "value": "Albania"},
    {"name": "Alemanha", "value": "Germany"},
    {"name": "Andorra", "value": "Andorra"},
    {"name": "Angola", "value": "Angola"},
    {"name": "Antiga e Barbuda", "value": "Antigua and Barbuda"},
    {"name": "Arábia Saudita", "value": "Saudi Arabia"},
    {"name": "Argélia", "value": "Algeria"},
    {"name": "Argentina", "value": "Argentina"},
    {"name": "Armênia", "value": "Armenia"},
    {"name": "Austrália", "value": "Australia"},
    {"name": "Áustria", "value": "Austria"},
    {"name": "Azerbaijão", "value": "Azerbaijan"},
    {"name": "Bahamas", "value": "Bahamas"},
    {"name": "Bangladesh", "value": "Bangladesh"},
    {"name": "Barbados", "value": "Barbados"},
    {"name": "Barein", "value": "Bahrain"},
    {"name": "Bélgica", "value": "Belgium"},
    {"name": "Belize", "value": "Belize"},
    {"name": "Benin", "value": "Benin"},
    {"name": "Bielorrússia", "value": "Belarus"},
    {"name": "Bolívia", "value": "Bolivia"},
    {"name": "Bósnia e Herzegovina", "value": "Bosnia and Herzegovina"},
    {"name": "Botsuana", "value": "Botswana"},
    {"name": "Brasil", "value": "Brazil"},
    {"name": "Brunei", "value": "Brunei"},
    {"name": "Bulgária", "value": "Bulgaria"},
    {"name": "Burquina Faso", "value": "Burkina Faso"},
    {"name": "Burundi", "value": "Burundi"},
    {"name": "Butão", "value": "Bhutan"},
    {"name": "Cabo Verde", "value": "Cape Verde"},
    {"name": "Camarões", "value": "Cameroon"},
    {"name": "Camboja", "value": "Cambodia"},
    {"name": "Canadá", "value": "Canada"},
    {"name": "Catar", "value": "Qatar"},
    {"name": "Cazaquistão", "value": "Kazakhstan"},
    {"name": "Chade", "value": "Chad"},
    {"name": "Chile", "value": "Chile"},
    {"name": "China", "value": "China"},
    {"name": "Chipre", "value": "Cyprus"},
    {"name": "Cingapura", "value": "Singapore"},
    {"name": "Colômbia", "value": "Colombia"},
    {"name": "Comores", "value": "Comoros"},
    {"name": "Congo", "value": "Congo"},
    {"name": "Coreia do Norte", "value": "North Korea"},
    {"name": "Coreia do Sul", "value": "South Korea"},
    {"name": "Costa do Marfim", "value": "Ivory Coast"},
    {"name": "Costa Rica", "value": "Costa Rica"},
    {"name": "Croácia", "value": "Croatia"},
    {"name": "Cuba", "value": "Cuba"},
    {"name": "Dinamarca", "value": "Denmark"},
    {"name": "Djibuti", "value": "Djibouti"},
    {"name": "Dominica", "value": "Dominica"},
    {"name": "Egito", "value": "Egypt"},
    {"name": "El Salvador", "value": "El Salvador"},
    {"name": "Emirados Árabes Unidos", "value": "United Arab Emirates"},
    {"name": "Equador", "value": "Ecuador"},
    {"name": "Eritreia", "value": "Eritrea"},
    {"name": "Eslováquia", "value": "Slovakia"},
    {"name": "Eslovênia", "value": "Slovenia"},
    {"name": "Espanha", "value": "Spain"},
    {"name": "Estados Unidos", "value": "United States"},
    {"name": "Estônia", "value": "Estonia"},
    {"name": "Etiópia", "value": "Ethiopia"},
    {"name": "Fiji", "value": "Fiji"},
    {"name": "Filipinas", "value": "Philippines"},
    {"name": "Finlândia", "value": "Finland"},
    {"name": "França", "value": "France"},
    {"name": "Gabão", "value": "Gabon"},
    {"name": "Gâmbia", "value": "Gambia"},
    {"name": "Gana", "value": "Ghana"},
    {"name": "Geórgia", "value": "Georgia"},
    {"name": "Granada", "value": "Grenada"},
    {"name": "Grécia", "value": "Greece"},
    {"name": "Guatemala", "value": "Guatemala"},
    {"name": "Guiana", "value": "Guyana"},
    {"name": "Guiné", "value": "Guinea"},
    {"name": "Guiné Equatorial", "value": "Equatorial Guinea"},
    {"name": "Guiné-Bissau", "value": "Guinea-Bissau"},
    {"name": "Haiti", "value": "Haiti"},
    {"name": "Holanda", "value": "Netherlands"},
    {"name": "Honduras", "value": "Honduras"},
    {"name": "Hungria", "value": "Hungary"},
    {"name": "Iémen", "value": "Yemen"},
    {"name": "Ilhas Marshall", "value": "Marshall Islands"},
    {"name": "Ilhas Salomão", "value": "Solomon Islands"},
    {"name": "Índia", "value": "India"},
    {"name": "Indonésia", "value": "Indonesia"},
    {"name": "Irã", "value": "Iran"},
    {"name": "Iraque", "value": "Iraq"},
    {"name": "Irlanda", "value": "Ireland"},
    {"name": "Islândia", "value": "Iceland"},
    {"name": "Israel", "value": "Israel"},
    {"name": "Itália", "value": "Italy"},
    {"name": "Jamaica", "value": "Jamaica"},
    {"name": "Japão", "value": "Japan"},
    {"name": "Jordânia", "value": "Jordan"},
    {"name": "Kiribati", "value": "Kiribati"},
    {"name": "Kosovo", "value": "Kosovo"},
    {"name": "Kuwait", "value": "Kuwait"},
    {"name": "Laos", "value": "Laos"},
    {"name": "Lesoto", "value": "Lesotho"},
    {"name": "Letônia", "value": "Latvia"},
    {"name": "Líbano", "value": "Lebanon"},
    {"name": "Libéria", "value": "Liberia"},
    {"name": "Líbia", "value": "Libya"},
    {"name": "Liechtenstein", "value": "Liechtenstein"},
    {"name": "Lituânia", "value": "Lithuania"},
    {"name": "Luxemburgo", "value": "Luxembourg"},
    {"name": "Macedônia do Norte", "value": "North Macedonia"},
    {"name": "Madagáscar", "value": "Madagascar"},
    {"name": "Malásia", "value": "Malaysia"},
    {"name": "Malaui", "value": "Malawi"},
    {"name": "Maldivas", "value": "Maldives"},
    {"name": "Mali", "value": "Mali"},
    {"name": "Malta", "value": "Malta"},
    {"name": "Marrocos", "value": "Morocco"},
    {"name": "Maurícia", "value": "Mauritius"},
    {"name": "Mauritânia", "value": "Mauritania"},
    {"name": "México", "value": "Mexico"},
    {"name": "Micronésia", "value": "Micronesia"},
    {"name": "Moçambique", "value": "Mozambique"},
    {"name": "Moldávia", "value": "Moldova"},
    {"name": "Mônaco", "value": "Monaco"},
    {"name": "Mongólia", "value": "Mongolia"},
    {"name": "Montenegro", "value": "Montenegro"},
    {"name": "Namíbia", "value": "Namibia"},
    {"name": "Nauru", "value": "Nauru"},
    {"name": "Nepal", "value": "Nepal"},
    {"name": "Nicarágua", "value": "Nicaragua"},
    {"name": "Níger", "value": "Niger"},
    {"name": "Nigéria", "value": "Nigeria"},
    {"name": "Niue", "value": "Niue"},
    {"name": "Noruega", "value": "Norway"},
    {"name": "Nova Zelândia", "value": "New Zealand"},
    {"name": "Omã", "value": "Oman"},
    {"name": "Palau", "value": "Palau"},
    {"name": "Palestina", "value": "Palestine"},
    {"name": "Panamá", "value": "Panama"},
    {"name": "Papua-Nova Guiné", "value": "Papua New Guinea"},
    {"name": "Paquistão", "value": "Pakistan"},
    {"name": "Paraguai", "value": "Paraguay"},
    {"name": "Peru", "value": "Peru"},
    {"name": "Polônia", "value": "Poland"},
    {"name": "Portugal", "value": "Portugal"},
    {"name": "Quênia", "value": "Kenya"},
    {"name": "Quirguistão", "value": "Kyrgyzstan"},
    {"name": "Quiribati", "value": "Kiribati"},
    {"name": "Reino Unido", "value": "United Kingdom"},
    {"name": "República Centro-Africana", "value": "Central African Republic"},
    {"name": "República Checa", "value": "Czech Republic"},
    {"name": "República Democrática do Congo", "value": "Democratic Republic of the Congo"},
    {"name": "República Dominicana", "value": "Dominican Republic"},
    {"name": "Romênia", "value": "Romania"},
    {"name": "Ruanda", "value": "Rwanda"},
    {"name": "Rússia", "value": "Russia"},
    {"name": "Salvador", "value": "El Salvador"},
    {"name": "Samoa", "value": "Samoa"},
    {"name": "Santa Lúcia", "value": "Saint Lucia"},
    {"name": "São Cristóvão e Neves", "value": "Saint Kitts and Nevis"},
    {"name": "São Marinho", "value": "San Marino"},
    {"name": "São Tomé e Príncipe", "value": "Sao Tome and Principe"},
    {"name": "São Vicente e Granadinas", "value": "Saint Vincent and the Grenadines"},
    {"name": "Seicheles", "value": "Seychelles"},
    {"name": "Senegal", "value": "Senegal"},
    {"name": "Serra Leoa", "value": "Sierra Leone"},
    {"name": "Sérvia", "value": "Serbia"},
    {"name": "Singapura", "value": "Singapore"},
    {"name": "Síria", "value": "Syria"},
    {"name": "Somália", "value": "Somalia"},
    {"name": "Sri Lanka", "value": "Sri Lanka"},
    {"name": "Suazilândia", "value": "Eswatini"},
    {"name": "Sudão", "value": "Sudan"},
    {"name": "Sudão do Sul", "value": "South Sudan"},
    {"name": "Suécia", "value": "Sweden"},
    {"name": "Suíça", "value": "Switzerland"},
    {"name": "Suriname", "value": "Suriname"},
    {"name": "Tailândia", "value": "Thailand"},
    {"name": "Taiwan", "value": "Taiwan"},
    {"name": "Tajiquistão", "value": "Tajikistan"},
    {"name": "Tanzânia", "value": "Tanzania"},
    {"name": "Timor-Leste", "value": "East Timor"},
    {"name": "Togo", "value": "Togo"},
    {"name": "Tonga", "value": "Tonga"},
    {"name": "Trindade e Tobago", "value": "Trinidad and Tobago"},
    {"name": "Tunísia", "value": "Tunisia"},
    {"name": "Turcomenistão", "value": "Turkmenistan"},
    {"name": "Turquia", "value": "Turkey"},
    {"name": "Tuvalu", "value": "Tuvalu"},
    {"name": "Ucrânia", "value": "Ukraine"},
    {"name": "Uganda", "value": "Uganda"},
    {"name": "Uruguai", "value": "Uruguay"},
    {"name": "Uzbequistão", "value": "Uzbekistan"},
    {"name": "Vanuatu", "value": "Vanuatu"},
    {"name": "Vaticano", "value": "Vatican City"},
    {"name": "Venezuela", "value": "Venezuela"},
    {"name": "Vietnã", "value": "Vietnam"},
    {"name": "Zâmbia", "value": "Zambia"},
    {"name": "Zimbábue", "value": "Zimbabwe"}
]

export const countryListEn = [
    {"name": "Afghanistan", "value": "Afghanistan"},
    {"name": "South Africa", "value": "South Africa"},
    {"name": "Albania", "value": "Albania"},
    {"name": "Germany", "value": "Germany"},
    {"name": "Andorra", "value": "Andorra"},
    {"name": "AnAngolagola", "value": "Angola"},
    {"name": "Antigua and Barbuda", "value": "Antigua and Barbuda"},
    {"name": "Saudi Arabia", "value": "Saudi Arabia"},
    {"name": "Algeria", "value": "Algeria"},
    {"name": "Argentina", "value": "Argentina"},
    {"name": "Armenia", "value": "Armenia"},
    {"name": "Australia", "value": "Australia"},
    {"name": "Austria", "value": "Austria"},
    {"name": "Azerbaijan", "value": "Azerbaijan"},
    {"name": "Bahamas", "value": "Bahamas"},
    {"name": "Bangladesh", "value": "Bangladesh"},
    {"name": "Barbados", "value": "Barbados"},
    {"name": "Bahrain", "value": "Bahrain"},
    {"name": "Belgium", "value": "Belgium"},
    {"name": "Belize", "value": "Belize"},
    {"name": "Benin", "value": "Benin"},
    {"name": "Belarus", "value": "Belarus"},
    {"name": "Bolivia", "value": "Bolivia"},
    {"name": "Bosnia and Herzegovina", "value": "Bosnia and Herzegovina"},
    {"name": "Botswana", "value": "Botswana"},
    {"name": "Brazil", "value": "Brazil"},
    {"name": "Brunei", "value": "Brunei"},
    {"name": "Bulgaria", "value": "Bulgaria"},
    {"name": "Burkina Faso", "value": "Burkina Faso"},
    {"name": "Burundi", "value": "Burundi"},
    {"name": "Bhutan", "value": "Bhutan"},
    {"name": "Cape Verde", "value": "Cape Verde"},
    {"name": "Cameroon", "value": "Cameroon"},
    {"name": "Cambodia", "value": "Cambodia"},
    {"name": "Canada", "value": "Canada"},
    {"name": "Qatar", "value": "Qatar"},
    {"name": "Kazakhstan", "value": "Kazakhstan"},
    {"name": "Chad", "value": "Chad"},
    {"name": "Chile", "value": "Chile"},
    {"name": "China", "value": "China"},
    {"name": "Cyprus", "value": "Cyprus"},
    {"name": "Singapore", "value": "Singapore"},
    {"name": "Colombia", "value": "Colombia"},
    {"name": "Comoros", "value": "Comoros"},
    {"name": "Congo", "value": "Congo"},
    {"name": "North Korea", "value": "North Korea"},
    {"name": "South Korea", "value": "South Korea"},
    {"name": "Ivory Coast", "value": "Ivory Coast"},
    {"name": "Costa Rica", "value": "Costa Rica"},
    {"name": "Croatia", "value": "Croatia"},
    {"name": "Cuba", "value": "Cuba"},
    {"name": "Denmark", "value": "Denmark"},
    {"name": "Djibouti", "value": "Djibouti"},
    {"name": "Dominica", "value": "Dominica"},
    {"name": "Egypt", "value": "Egypt"},
    {"name": "El Salvador", "value": "El Salvador"},
    {"name": "United Arab Emirates", "value": "United Arab Emirates"},
    {"name": "Ecuador", "value": "Ecuador"},
    {"name": "Eritrea", "value": "Eritrea"},
    {"name": "Slovakia", "value": "Slovakia"},
    {"name": "Slovenia", "value": "Slovenia"},
    {"name": "Spain", "value": "Spain"},
    {"name": "United States", "value": "United States"},
    {"name": "Estonia", "value": "Estonia"},
    {"name": "Ethiopia", "value": "Ethiopia"},
    {"name": "Fiji", "value": "Fiji"},
    {"name": "Philippines", "value": "Philippines"},
    {"name": "Finland", "value": "Finland"},
    {"name": "France", "value": "France"},
    {"name": "Gabon", "value": "Gabon"},
    {"name": "Gambia", "value": "Gambia"},
    {"name": "Ghana", "value": "Ghana"},
    {"name": "Georgia", "value": "Georgia"},
    {"name": "Grenada", "value": "Grenada"},
    {"name": "Greece", "value": "Greece"},
    {"name": "Guatemala", "value": "Guatemala"},
    {"name": "Guyana", "value": "Guyana"},
    {"name": "Guinea", "value": "Guinea"},
    {"name": "Equatorial Guinea", "value": "Equatorial Guinea"},
    {"name": "Guinea-Bissau", "value": "Guinea-Bissau"},
    {"name": "Haiti", "value": "Haiti"},
    {"name": "Netherlands", "value": "Netherlands"},
    {"name": "Honduras", "value": "Honduras"},
    {"name": "Hungary", "value": "Hungary"},
    {"name": "Yemen", "value": "Yemen"},
    {"name": "Marshall Islands", "value": "Marshall Islands"},
    {"name": "ISolomon Islands", "value": "Solomon Islands"},
    {"name": "India", "value": "India"},
    {"name": "Indonesia", "value": "Indonesia"},
    {"name": "Iran", "value": "Iran"},
    {"name": "Iraq", "value": "Iraq"},
    {"name": "Ireland", "value": "Ireland"},
    {"name": "Iceland", "value": "Iceland"},
    {"name": "Israel", "value": "Israel"},
    {"name": "Italy", "value": "Italy"},
    {"name": "Jamaica", "value": "Jamaica"},
    {"name": "Japan", "value": "Japan"},
    {"name": "Jordan", "value": "Jordan"},
    {"name": "Kiribati", "value": "Kiribati"},
    {"name": "Kosovo", "value": "Kosovo"},
    {"name": "Kuwait", "value": "Kuwait"},
    {"name": "Laos", "value": "Laos"},
    {"name": "Lesotho", "value": "Lesotho"},
    {"name": "Latvia", "value": "Latvia"},
    {"name": "Lebanon", "value": "Lebanon"},
    {"name": "Liberia", "value": "Liberia"},
    {"name": "Libya", "value": "Libya"},
    {"name": "Liechtenstein", "value": "Liechtenstein"},
    {"name": "Lithuania", "value": "Lithuania"},
    {"name": "Luxembourg", "value": "Luxembourg"},
    {"name": "North Macedonia", "value": "North Macedonia"},
    {"name": "Madagascar", "value": "Madagascar"},
    {"name": "Malaysia", "value": "Malaysia"},
    {"name": "Malawi", "value": "Malawi"},
    {"name": "Maldives", "value": "Maldives"},
    {"name": "Mali", "value": "Mali"},
    {"name": "Malta", "value": "Malta"},
    {"name": "Morocco", "value": "Morocco"},
    {"name": "Mauritius", "value": "Mauritius"},
    {"name": "Mauritania", "value": "Mauritania"},
    {"name": "Mexico", "value": "Mexico"},
    {"name": "Micronesia", "value": "Micronesia"},
    {"name": "Mozambique", "value": "Mozambique"},
    {"name": "Moldova", "value": "Moldova"},
    {"name": "Monaco", "value": "Monaco"},
    {"name": "Mongolia", "value": "Mongolia"},
    {"name": "Montenegro", "value": "Montenegro"},
    {"name": "Namibia", "value": "Namibia"},
    {"name": "Nauru", "value": "Nauru"},
    {"name": "Nepal", "value": "Nepal"},
    {"name": "Nicaragua", "value": "Nicaragua"},
    {"name": "Niger", "value": "Niger"},
    {"name": "Nigeria", "value": "Nigeria"},
    {"name": "Niue", "value": "Niue"},
    {"name": "Norway", "value": "Norway"},
    {"name": "New Zealand", "value": "New Zealand"},
    {"name": "Oman", "value": "Oman"},
    {"name": "Palau", "value": "Palau"},
    {"name": "Palestine", "value": "Palestine"},
    {"name": "Panama", "value": "Panama"},
    {"name": "Papua New Guinea", "value": "Papua New Guinea"},
    {"name": "Pakistan", "value": "Pakistan"},
    {"name": "Paraguay", "value": "Paraguay"},
    {"name": "Peru", "value": "Peru"},
    {"name": "Poland", "value": "Poland"},
    {"name": "Portugal", "value": "Portugal"},
    {"name": "Kenya", "value": "Kenya"},
    {"name": "Kyrgyzstan", "value": "Kyrgyzstan"},
    {"name": "Kiribati", "value": "Kiribati"},
    {"name": "United Kingdom", "value": "United Kingdom"},
    {"name": "Central African Republic", "value": "Central African Republic"},
    {"name": "Czech Republic", "value": "Czech Republic"},
    {"name": "Democratic Republic of the Congo", "value": "Democratic Republic of the Congo"},
    {"name": "Dominican Republic", "value": "Dominican Republic"},
    {"name": "Romania", "value": "Romania"},
    {"name": "Rwanda", "value": "Rwanda"},
    {"name": "Russia", "value": "Russia"},
    {"name": "El Salvador", "value": "El Salvador"},
    {"name": "Samoa", "value": "Samoa"},
    {"name": "Saint Lucia", "value": "Saint Lucia"},
    {"name": "Saint Kitts and Nevis", "value": "Saint Kitts and Nevis"},
    {"name": "San Marino", "value": "San Marino"},
    {"name": "Sao Tome and Principe", "value": "Sao Tome and Principe"},
    {"name": "Saint Vincent and the Grenadines", "value": "Saint Vincent and the Grenadines"},
    {"name": "Seychelles", "value": "Seychelles"},
    {"name": "Senegal", "value": "Senegal"},
    {"name": "Sierra Leone", "value": "Sierra Leone"},
    {"name": "Serbia", "value": "Serbia"},
    {"name": "Singapore", "value": "Singapore"},
    {"name": "Syria", "value": "Syria"},
    {"name": "Somalia", "value": "Somalia"},
    {"name": "Sri Lanka", "value": "Sri Lanka"},
    {"name": "Eswatini", "value": "Eswatini"},
    {"name": "Sudan", "value": "Sudan"},
    {"name": "South Sudan", "value": "South Sudan"},
    {"name": "Sweden", "value": "Sweden"},
    {"name": "Switzerland", "value": "Switzerland"},
    {"name": "Suriname", "value": "Suriname"},
    {"name": "Thailand", "value": "Thailand"},
    {"name": "Taiwan", "value": "Taiwan"},
    {"name": "Tajikistan", "value": "Tajikistan"},
    {"name": "Tanzania", "value": "Tanzania"},
    {"name": "East Timor", "value": "East Timor"},
    {"name": "Togo", "value": "Togo"},
    {"name": "Tonga", "value": "Tonga"},
    {"name": "Trinidad and Tobago", "value": "Trinidad and Tobago"},
    {"name": "Tunisia", "value": "Tunisia"},
    {"name": "Turkmenistan", "value": "Turkmenistan"},
    {"name": "Turkey", "value": "Turkey"},
    {"name": "Tuvalu", "value": "Tuvalu"},
    {"name": "Ukraine", "value": "Ukraine"},
    {"name": "Uganda", "value": "Uganda"},
    {"name": "Uruguay", "value": "Uruguay"},
    {"name": "Uzbekistan", "value": "Uzbekistan"},
    {"name": "Vanuatu", "value": "Vanuatu"},
    {"name": "Vatican City", "value": "Vatican City"},
    {"name": "Venezuela", "value": "Venezuela"},
    {"name": "Vietnam", "value": "Vietnam"},
    {"name": "Zambia", "value": "Zambia"},
    {"name": "Zimbabwe", "value": "Zimbabwe"}
]